# Database Configuration
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/hospital_queue_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
jdbc.username=root
jdbc.password=Gopika@2006
jdbc.pool.initialSize=5
jdbc.pool.maxTotal=20
